name: Deploying startpage to Github Pages

on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build
        run: bun install

      - name: Deploy
        run: |
          git config --global user.name 'NotTacoz'
          git config --global user.email 'tacozpvp@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          bun run deploy
